<#macro layout siteTitle pageTitle="" basePath="" locale="en" docSwitcher=[] versionSwitcher=[] currentComponentId="" currentVersionStr="" currentVersion={} currentPagePath="" navigation={} breadcrumbs=[] prevPage={} nextPage={}>
<!DOCTYPE html>
<html lang="${locale}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><#if pageTitle?has_content>${pageTitle} - </#if>${siteTitle}</title>
    <link rel="stylesheet" href="${basePath}/site-assets/styles.css">
    <#nested "head">
</head>
<body>
    <header class="site-header">
        <div class="header-content">
            <a href="${basePath}/" class="site-title">${siteTitle}</a>
            <#if docSwitcher?has_content>
                <nav class="doc-switcher">
                    <label for="doc-switch">Documentation:</label>
                    <select id="doc-switch" onchange="window.location.href=this.value">
                        <option disabled>Documentation</option>
                        <#list docSwitcher as doc>
                            <option value="${basePath}/${doc.id}/${doc.defaultVersion}/"
                                <#if currentComponentId == doc.id>selected</#if>>
                                ${doc.displayName}
                            </option>
                        </#list>
                    </select>
                </nav>
            </#if>
            <#if versionSwitcher?has_content>
                <nav class="version-switcher">
                    <label for="version-switch">Version:</label>
                    <select id="version-switch" onchange="window.location.href=this.value">
                        <option disabled>Version</option>
                        <#list versionSwitcher as ver>
                            <option value="${basePath}/${currentComponentId}/${ver.version}/<#if currentPagePath?has_content>${currentPagePath}<#else></#if>"
                                <#if currentVersionStr == ver.version>selected</#if>>
                                ${ver.displayVersion}
                            </option>
                        </#list>
                    </select>
                </nav>
            </#if>
        </div>
    </header>

    <div class="layout">
        <#if navigation?has_content && navigation.items?has_content>
        <aside class="sidebar">
            <nav class="sidebar-nav">
                <#include "sidebar-nav.ftl">
            </nav>
        </aside>
        </#if>

        <main class="content">
            <#if breadcrumbs?has_content && breadcrumbs?size gt 1>
            <nav class="breadcrumbs">
                <#list breadcrumbs as crumb>
                    <#if crumb_index gt 0><span class="separator">/</span></#if>
                    <#if crumb.route?has_content>
                        <a href="${basePath}${crumb.route}">${crumb.title}</a>
                    <#else>
                        <span class="current">${crumb.title}</span>
                    </#if>
                </#list>
            </nav>
            </#if>

            <#nested "content">

            <#if prevPage?has_content || nextPage?has_content>
            <nav class="prev-next">
                <#if prevPage?has_content>
                    <a href="${basePath}${prevPage.route}" class="prev">&larr; ${prevPage.title}</a>
                </#if>
                <#if nextPage?has_content>
                    <a href="${basePath}${nextPage.route}" class="next">${nextPage.title} &rarr;</a>
                </#if>
            </nav>
            </#if>
        </main>
    </div>

    <footer class="site-footer">
        <p>Generated by <a href="https://github.com/stefan/thoth">Thoth Biblios</a></p>
    </footer>
</body>
</html>
</#macro>
